### PR TITLE
Rendering first measure

### PR DESCRIPTION
**Pull request by drumnkyle**
This is mostly a test. The changes that are not in the sample app, should be checked in, but the ones in the sample app will likely be removed/changed.

### CODE REVIEW

**Comment by drumnkyle** [comment]
screen shot 2017-04-15 at 4 43 11 pm

**Comment by drumnkyle** [comment]
screen shot 2017-04-15 at 9 10 34 pm

**Comment by johndpope** [comment]
fyi - 
https://github.com/cprovatas/Consonance

**Comment by drumnkyle** [comment]
Thanks for the pointer. I will look into that implementation. We’ve done a lot of work on the core project, but we’re still trying to figure out the rendering portion so that will be very helpful.

**Pull request closed without merging**
